### PR TITLE
Pass the job that raised to the error_handler

### PR DESCRIPTION
**Pull request by dschaub**
/domain @samandmoore @Jaco-Pretorius @effron 

this would be a breaking change to any app that implements `error_handler`, right?

### CODE REVIEW

**Comment by samandmoore** [comment]
> this would be a breaking change to any app that implements error_handler, right?

i don't think it would be a breaking change because `error_handler` is a block and not a lambda. so, it doesn't care how many args you pass it (i think). it will just bind the ones that it can bind and ignore the rest. so as long as you aren't changing the order of the args, it's fine.

**Comment by dschaub** [comment]
any idea who actually owns this repo so we can set it up in travis?

**Comment by samandmoore** [comment]
> any idea who actually owns this repo so we can set it up in travis?

reust does. but i just toggled the thing in travis, i think.

**Comment by dschaub** [comment]
alright travis is hooked up and we're :100:

**Comment by samandmoore** [comment]
<<domainlgtm

p.s. @reustmd you gotta add prbot group to the repo so that nanda can dance.

**Comment by samandmoore** [comment]
nvm. it works.

**Pull request merged**
